import sqlmodel

"""Add is_uc to STEventModel

Revision ID: 2e72575386ec
Revises: 8858e8b41e15
Create Date: 2025-11-02 20:39:57.355134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e72575386ec'
down_revision: Union[str, None] = '8858e8b41e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('st_event', sa.Column('is_uc', sa.Boolean(), nullable=False))
    op.create_unique_constraint('_user_badge_uc', 'user_badges', ['user_id', 'badge_id'])
    op.create_unique_constraint('_user_league_uc', 'user_leagues', ['user_id', 'league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_league_uc', 'user_leagues', type_='unique')
    op.drop_constraint('_user_badge_uc', 'user_badges', type_='unique')
    op.drop_column('st_event', 'is_uc')
    # ### end Alembic commands ###
