import sqlmodel

"""Add is_micro_task to STTaskModel

Revision ID: 4e9937303b19
Revises: 2e72575386ec
Create Date: 2025-11-12 01:02:28.135063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9937303b19'
down_revision: Union[str, None] = '2e72575386ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('st_task', sa.Column('is_micro_task', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_league_uc', 'user_leagues', type_='unique')
    op.drop_constraint('_user_badge_uc', 'user_badges', type_='unique')
    # ### end Alembic commands ###
