import sqlmodel

"""Adiciona traducoes para tags e outras alteracoes

Revision ID: 8858e8b41e15
Revises: eb4b19e63e4c
Create Date: 2025-10-21 12:23:54.849555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8858e8b41e15'
down_revision: Union[str, None] = 'eb4b19e63e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('user_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    #op.create_unique_constraint('_user_badge_uc', 'user_badges', ['user_id', 'badge_id'])
    #op.create_unique_constraint('_user_league_uc', 'user_leagues', ['user_id', 'league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_league_uc', 'user_leagues', type_='unique')
    op.drop_constraint('_user_badge_uc', 'user_badges', type_='unique')
    op.drop_column('challenge', 'user_answer')
    # ### end Alembic commands ###
