import sqlmodel

"""Add task_id foreign key to st_event

Revision ID: 8911d6fa29db
Revises: db50935257fe
Create Date: 2025-11-16 20:46:02.840421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8911d6fa29db'
down_revision: Union[str, None] = 'db50935257fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('st_event', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('st_event', sa.Column('task_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_st_event_task_composite', 'st_event', 'st_task', ['task_id', 'task_user_id'], ['id', 'user_id'])
    op.alter_column('st_file', 'text',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_unique_constraint('_user_badge_uc', 'user_badges', ['user_id', 'badge_id'])
    op.create_unique_constraint('_user_league_uc', 'user_leagues', ['user_id', 'league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_league_uc', 'user_leagues', type_='unique')
    op.drop_constraint('_user_badge_uc', 'user_badges', type_='unique')
    op.alter_column('st_file', 'text',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('fk_st_event_task_composite', 'st_event', type_='foreignkey')
    op.drop_column('st_event', 'task_user_id')
    op.drop_column('st_event', 'task_id')
    # ### end Alembic commands ###
