import sqlmodel

"""Refactor Archives for Subfolders

Revision ID: a5fa6ca63cc4
Revises: b0e72a09c0ef
Create Date: 2026-03-08 19:55:48.194097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fa6ca63cc4'
down_revision: Union[str, None] = 'b0e72a09c0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_archive_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_archive_id'], ['st_archive.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', 'parent_archive_id', name='uq_archive_name_per_folder')
    )
    op.create_index(op.f('ix_st_archive_user_id'), 'st_archive', ['user_id'], unique=False)
    op.create_table('st_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['st_archive.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'archive_id', name='uq_file_name_per_folder')
    )
    op.create_index(op.f('ix_st_file_archive_id'), 'st_file', ['archive_id'], unique=False)
    op.create_unique_constraint('_user_badge_uc', 'user_badges', ['user_id', 'badge_id'])
    op.create_unique_constraint('_user_league_uc', 'user_leagues', ['user_id', 'league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_league_uc', 'user_leagues', type_='unique')
    op.drop_constraint('_user_badge_uc', 'user_badges', type_='unique')
    op.drop_index(op.f('ix_st_file_archive_id'), table_name='st_file')
    op.drop_table('st_file')
    op.drop_index(op.f('ix_st_archive_user_id'), table_name='st_archive')
    op.drop_table('st_archive')
    # ### end Alembic commands ###
