import sqlmodel

"""Substituir daily_energy por mood_logs

Revision ID: a994e1ff294b
Revises: 8911d6fa29db
Create Date: 2026-01-10 03:39:17.828858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a994e1ff294b'
down_revision: Union[str, None] = '8911d6fa29db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('_user_badge_uc', 'user_badges', ['user_id', 'badge_id'])
    #op.create_unique_constraint('_user_league_uc', 'user_leagues', ['user_id', 'league_id'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_league_uc', 'user_leagues', type_='unique')
    op.drop_constraint('_user_badge_uc', 'user_badges', type_='unique')
    # ### end Alembic commands ###
