import sqlmodel

"""add fenix_id and email to user

Revision ID: fb7d8be26c83
Revises: b709a72fc97a
Create Date: 2026-01-31 20:52:24.129306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7d8be26c83'
down_revision: Union[str, None] = 'b709a72fc97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fenix_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('institutional_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_fenix_id'), 'user', ['fenix_id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    #op.create_unique_constraint('_user_badge_uc', 'user_badges', ['user_id', 'badge_id'])
    #op.create_unique_constraint('_user_league_uc', 'user_leagues', ['user_id', 'league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('_user_league_uc', 'user_leagues', type_='unique')
    #op.drop_constraint('_user_badge_uc', 'user_badges', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_fenix_id'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'institutional_email')
    op.drop_column('user', 'fenix_id')
    # ### end Alembic commands ###
