services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:80"
    depends_on:
      postgresdb:
        condition: service_healthy
    links:
      - postgresdb
    env_file:
      - env/backend

  postgresdb:
    hostname: localhost
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    env_file:
      - env/postgres

  frontend-acedemic-tracker:
    build:
      context: ../frontend/study-tracker
    ports:
      - "3000:3002"
    env_file:
      - env/acedemic-tracker

volumes:
  postgresdb-data:
    driver: local
